import type { Hono } from "npm:hono";
import { supabaseAdmin } from "./shared.ts";
const PREFIX = "/make-server-3ba8d4df";
const MS_SCOPES = "offline_access https://graph.microsoft.com/Mail.ReadWrite https://graph.microsoft.com/Mail.Send https://graph.microsoft.com/User.Read";
class MsNotConnectedError extends Error { constructor() { super("Microsoft 365 is not connected yet"); this.name = "MsNotConnectedError"; } }
function redirectUri(): string { return `${Deno.env.get("SUPABASE_URL")}/functions/v1/make-server-3ba8d4df/microsoft/callback`; }
async function getMsClientConfig(db: any): Promise<{ clientId: string; clientSecret: string; tenantId: string }> { const { data, error } = await db.from("app_secrets").select("key, value").in("key", ["ms_client_id", "ms_client_secret", "ms_tenant_id"]); if (error) throw new Error(`Failed to load Microsoft config: ${error.message}`); const map = Object.fromEntries((data ?? []).map((r: any) => [r.key, r.value])); if (!map.ms_client_id || !map.ms_client_secret || !map.ms_tenant_id) throw new Error("Microsoft 365 is not configured yet"); return { clientId: map.ms_client_id, clientSecret: map.ms_client_secret, tenantId: map.ms_tenant_id }; }
async function getValidMsToken(db: any): Promise<string> { const { data, error } = await db.from("tt_ms_auth").select("*").eq("id", 1).maybeSingle(); if (error) throw new Error(`Failed to load Microsoft auth: ${error.message}`); if (!data?.refresh_token) throw new MsNotConnectedError(); const expiresAtMs = data.expires_at ? new Date(data.expires_at).getTime() : 0; if (data.access_token && expiresAtMs > Date.now() + 60000) return data.access_token; const { clientId, clientSecret, tenantId } = await getMsClientConfig(db); const body = new URLSearchParams({ client_id: clientId, client_secret: clientSecret, grant_type: "refresh_token", refresh_token: data.refresh_token, scope: MS_SCOPES }); const res = await fetch(`https://login.microsoftonline.com/${tenantId}/oauth2/v2.0/token`, { method: "POST", headers: { "Content-Type": "application/x-www-form-urlencoded" }, body }); const json = await res.json().catch(() => ({})); if (!res.ok) throw new Error(`Microsoft token refresh failed: ${json.error_description || json.error || res.statusText}`); const accessToken = json.access_token; const refreshToken = json.refresh_token ?? data.refresh_token; const expiresAt = new Date(Date.now() + (json.expires_in ?? 3600) * 1000).toISOString(); const { error: updateErr } = await db.from("tt_ms_auth").update({ access_token: accessToken, refresh_token: refreshToken, expires_at: expiresAt, updated_at: new Date().toISOString() }).eq("id", 1); if (updateErr) console.error("Failed to persist refreshed Microsoft token", updateErr); return accessToken; }
async function graphApi(token: string, path: string, init: RequestInit = {}): Promise<any> { const res = await fetch(`https://graph.microsoft.com/v1.0${path}`, { ...init, headers: { Authorization: `Bearer ${token}`, "Content-Type": "application/json", ...(init.headers ?? {}) } }); const text = await res.text(); let json: any = null; if (text) { try { json = JSON.parse(text); } catch { json = text; } } if (!res.ok) { const msg = json?.error?.message || (typeof json === "string" ? json : res.statusText); throw Object.assign(new Error(`Microsoft Graph error (${res.status}): ${msg}`), { status: res.status }); } return json; }
async function withMs(c: any, db: any, fn: (token: string) => Promise<any>) { try { const token = await getValidMsToken(db); return await fn(token); } catch (e) { if (e instanceof MsNotConnectedError) return c.json({ error: "not_connected" }, 409); console.error("Microsoft Graph request failed", e); return c.json({ error: String(e instanceof Error ? e.message : e) }, 500); } }
const OVERDUE_RE = /overdue|payment reminder|past due|outstanding (payment|invoice|amount|balance)|final notice|second notice|breach of (the )?lease/i;
const BILL_RE = /invoice|tax invoice|statement|receipt|\bbill\b/i;
const AMOUNT_RE = /\$\s?([\d,]+\.\d{2})/;
function classifyEmail(m: any) { const subject = m.subject ?? ""; const preview = m.bodyPreview ?? ""; const text = `${subject} ${preview}`; const isOverdue = OVERDUE_RE.test(text); const isBill = isOverdue || BILL_RE.test(text); const amountMatch = text.match(AMOUNT_RE); const amount = amountMatch ? Number(amountMatch[1].replace(/,/g, "")) : null; const from = m.from?.emailAddress?.name || m.from?.emailAddress?.address || "Unknown sender"; return { id: m.id, subject, preview: preview.slice(0, 220), from, fromEmail: m.from?.emailAddress?.address ?? null, receivedAt: m.receivedDateTime, isRead: !!m.isRead, webLink: m.webLink ?? null, category: isOverdue ? "overdue" : isBill ? "bill" : "update", amount }; }
function mapInboxMessage(m: any) { return { id: m.id, subject: m.subject ?? "", preview: (m.bodyPreview ?? "").slice(0, 220), from: m.from?.emailAddress?.name || m.from?.emailAddress?.address || "Unknown sender", fromEmail: m.from?.emailAddress?.address ?? null, receivedAt: m.receivedDateTime, isRead: !!m.isRead, hasAttachments: !!m.hasAttachments, webLink: m.webLink ?? null }; }
function oauthPage(title: string, body: string): string { return `<!doctype html><html><head><meta charset="utf-8"><title>${title}</title><style>\n      body{font-family:-apple-system,BlinkMacSystemFont,sans-serif;background:#000;color:#fff;display:flex;align-items:center;justify-content:center;height:100vh;margin:0;text-align:center;padding:24px;box-sizing:border-box}\n      div{max-width:340px}h1{font-size:16px;font-weight:600;margin-bottom:8px}p{font-size:13px;color:rgba(255,255,255,0.6);line-height:1.5}\n    </style></head><body><div><h1>${title}</h1><p>${body}</p></div><script>setTimeout(()=>window.close(),1800)</script></body></html>`; }

export function registerMicrosoftRoutes(app: Hono) {
  app.get(`${PREFIX}/microsoft/status`, async (c) => { const db = supabaseAdmin(); try { const { data } = await db.from("tt_ms_auth").select("refresh_token, display_name, mail").eq("id", 1).maybeSingle(); if (!data?.refresh_token) return c.json({ connected: false }); await getValidMsToken(db); return c.json({ connected: true, displayName: data.display_name ?? null, mail: data.mail ?? null }); } catch (e) { console.error("microsoft status failed", e); return c.json({ connected: false, error: String(e instanceof Error ? e.message : e) }); } });
  app.get(`${PREFIX}/microsoft/auth-url`, async (c) => { try { const db = supabaseAdmin(); const { clientId, tenantId } = await getMsClientConfig(db); const state = crypto.randomUUID(); const { error } = await db.from("tt_ms_oauth_state").upsert({ id: 1, state, created_at: new Date().toISOString() }); if (error) throw new Error(error.message); const params = new URLSearchParams({ client_id: clientId, response_type: "code", redirect_uri: redirectUri(), response_mode: "query", scope: MS_SCOPES, state }); return c.json({ url: `https://login.microsoftonline.com/${tenantId}/oauth2/v2.0/authorize?${params.toString()}` }); } catch (e) { console.error("microsoft auth-url failed", e); return c.json({ error: String(e instanceof Error ? e.message : e) }, 500); } });
  app.get(`${PREFIX}/microsoft/callback`, async (c) => { const page = (title: string, body: string) => c.html(oauthPage(title, body)); try { const url = new URL(c.req.url); const code = url.searchParams.get("code"); const state = url.searchParams.get("state"); if (url.searchParams.get("error")) return page("Connection cancelled", "Microsoft sign-in was cancelled. Close this window and try again."); if (!code || !state) return page("Something went wrong", "Missing authorization code. Close this window and try connecting again."); const db = supabaseAdmin(); const { data: stateRow } = await db.from("tt_ms_oauth_state").select("state").eq("id", 1).maybeSingle(); if (!stateRow || stateRow.state !== state) return page("Something went wrong", "This sign-in link expired or was already used. Close this window and try again."); const { clientId, clientSecret, tenantId } = await getMsClientConfig(db); const body = new URLSearchParams({ client_id: clientId, client_secret: clientSecret, grant_type: "authorization_code", code, redirect_uri: redirectUri(), scope: MS_SCOPES }); const res = await fetch(`https://login.microsoftonline.com/${tenantId}/oauth2/v2.0/token`, { method: "POST", headers: { "Content-Type": "application/x-www-form-urlencoded" }, body }); const json = await res.json().catch(() => ({})); if (!res.ok) throw new Error(json.error_description || json.error || res.statusText); const accessToken = json.access_token, refreshToken = json.refresh_token; const expiresAt = new Date(Date.now() + (json.expires_in ?? 3600) * 1000).toISOString(); let profile: any = {}; try { profile = await graphApi(accessToken, "/me"); } catch (e) { console.warn("Could not fetch Microsoft profile after connect", e); } const { error: upsertErr } = await db.from("tt_ms_auth").upsert({ id: 1, access_token: accessToken, refresh_token: refreshToken, expires_at: expiresAt, scope: json.scope ?? MS_SCOPES, ms_user_id: profile.id ?? null, display_name: profile.displayName ?? null, mail: profile.mail ?? profile.userPrincipalName ?? null, updated_at: new Date().toISOString() }); if (upsertErr) throw new Error(upsertErr.message); await db.from("tt_ms_oauth_state").delete().eq("id", 1); return page("Microsoft 365 connected", `Signed in as ${profile.displayName ?? "the mailbox"}. You can close this window.`); } catch (e) { console.error("microsoft callback failed", e); return page("Something went wrong", String(e instanceof Error ? e.message : e)); } });
  app.post(`${PREFIX}/microsoft/disconnect`, async (c) => { try { const db = supabaseAdmin(); const { error } = await db.from("tt_ms_auth").delete().eq("id", 1); if (error) throw new Error(error.message); return c.json({ ok: true }); } catch (e) { return c.json({ error: String(e instanceof Error ? e.message : e) }, 500); } });
  app.get(`${PREFIX}/microsoft/updates`, async (c) => { const db = supabaseAdmin(); const days = Math.min(Math.max(Number(c.req.query("days") ?? "1"), 1), 14); return withMs(c, db, async (token) => { const since = new Date(Date.now() - days * 86400000).toISOString(); const params = new URLSearchParams({ $filter: `receivedDateTime ge ${since}`, $select: "id,subject,from,receivedDateTime,bodyPreview,isRead,webLink", $orderby: "receivedDateTime desc", $top: "100" }); const all = ((await graphApi(token, `/me/mailFolders/inbox/messages?${params.toString()}`)).value ?? []).map(classifyEmail); const overdueBills = all.filter((m: any) => m.category === "overdue"); const bills = all.filter((m: any) => m.category === "bill"); const updates = all.filter((m: any) => m.category === "update"); return c.json({ since, total: all.length, overdueBills, bills, updates }); }); });
  app.get(`${PREFIX}/microsoft/inbox`, async (c) => { const db = supabaseAdmin(); const folder = (c.req.query("folder") || "inbox").trim() || "inbox"; const top = Math.min(Math.max(Number(c.req.query("top") ?? "25"), 1), 50); const skip = Math.max(Number(c.req.query("skip") ?? "0"), 0); const search = (c.req.query("search") || "").trim(); return withMs(c, db, async (token) => { const params = new URLSearchParams({ $select: "id,subject,from,receivedDateTime,bodyPreview,isRead,hasAttachments,webLink", $orderby: "receivedDateTime desc", $top: String(top), $skip: String(skip) }); if (search) { params.delete("$orderby"); params.set("$search", `"${search.replace(/"/g, "")}"`); } const folderPath = folder === "inbox" ? "inbox" : encodeURIComponent(folder); const messages = (await graphApi(token, `/me/mailFolders/${folderPath}/messages?${params.toString()}`)).value ?? []; return c.json({ messages: messages.map(mapInboxMessage), hasMore: messages.length === top }); }); });
  app.get(`${PREFIX}/microsoft/message/:id`, async (c) => { const db = supabaseAdmin(); const id = c.req.param("id"); return withMs(c, db, async (token) => { const params = new URLSearchParams({ $select: "id,subject,from,toRecipients,ccRecipients,receivedDateTime,body,isRead,hasAttachments,webLink" }); const msg = await graphApi(token, `/me/messages/${encodeURIComponent(id)}?${params.toString()}`); let attachments: any[] = []; if (msg.hasAttachments) { try { attachments = ((await graphApi(token, `/me/messages/${encodeURIComponent(id)}/attachments?$select=id,name,contentType,size,isInline`)).value ?? []).filter((a: any) => !a.isInline); } catch (e) { console.warn("Failed to load attachments for message", id, e); } } return c.json({ id: msg.id, subject: msg.subject ?? "", from: msg.from?.emailAddress?.name || msg.from?.emailAddress?.address || "Unknown sender", fromEmail: msg.from?.emailAddress?.address ?? null, to: (msg.toRecipients ?? []).map((r: any) => r.emailAddress?.address).filter(Boolean), cc: (msg.ccRecipients ?? []).map((r: any) => r.emailAddress?.address).filter(Boolean), receivedAt: msg.receivedDateTime, bodyHtml: msg.body?.contentType === "html" ? msg.body?.content : null, bodyText: msg.body?.contentType === "text" ? msg.body?.content : null, isRead: !!msg.isRead, webLink: msg.webLink ?? null, attachments: attachments.map((a: any) => ({ id: a.id, name: a.name, contentType: a.contentType, size: a.size })) }); }); });
  app.post(`${PREFIX}/microsoft/message/:id/read`, async (c) => { const db = supabaseAdmin(); const id = c.req.param("id"); const { isRead } = await c.req.json().catch(() => ({ isRead: true })); return withMs(c, db, async (token) => { await graphApi(token, `/me/messages/${encodeURIComponent(id)}`, { method: "PATCH", body: JSON.stringify({ isRead: !!isRead }) }); return c.json({ ok: true }); }); });
  app.delete(`${PREFIX}/microsoft/message/:id`, async (c) => { const db = supabaseAdmin(); const id = c.req.param("id"); return withMs(c, db, async (token) => { await graphApi(token, `/me/messages/${encodeURIComponent(id)}`, { method: "DELETE" }); return c.json({ ok: true }); }); });
  app.get(`${PREFIX}/microsoft/message/:id/attachments/:attachmentId`, async (c) => { const db = supabaseAdmin(); const id = c.req.param("id"); const attachmentId = c.req.param("attachmentId"); return withMs(c, db, async (token) => { const att = await graphApi(token, `/me/messages/${encodeURIComponent(id)}/attachments/${encodeURIComponent(attachmentId)}`); return c.json({ name: att.name, contentType: att.contentType, contentBytes: att.contentBytes ?? null }); }); });
  app.post(`${PREFIX}/microsoft/send`, async (c) => { const db = supabaseAdmin(); const { to, cc, subject, bodyHtml, replyToMessageId } = await c.req.json(); if (!Array.isArray(to) || to.length === 0) return c.json({ error: "At least one recipient is required" }, 400); if (!subject || !bodyHtml) return c.json({ error: "Subject and body are required" }, 400); return withMs(c, db, async (token) => { const message = { subject, body: { contentType: "HTML", content: bodyHtml }, toRecipients: to.map((addr: string) => ({ emailAddress: { address: addr } })), ccRecipients: (cc ?? []).map((addr: string) => ({ emailAddress: { address: addr } })) }; await graphApi(token, "/me/sendMail", { method: "POST", body: JSON.stringify({ message, saveToSentItems: true }) }); if (replyToMessageId) { try { await graphApi(token, `/me/messages/${encodeURIComponent(replyToMessageId)}`, { method: "PATCH", body: JSON.stringify({ isRead: true }) }); } catch (e) { console.warn("Failed to mark replied-to message as read", e); } } return c.json({ ok: true }); }); });
}

export { getValidMsToken, graphApi, MsNotConnectedError, withMs };
