import type { Hono } from "npm:hono";
import { supabaseAdmin } from "./shared.ts";
const PREFIX = "/make-server-3ba8d4df";
const SPOTIFY_SCOPES = ["user-read-playback-state", "user-modify-playback-state", "user-read-currently-playing", "user-read-email", "user-read-private"].join(" ");
class SpotifyNotConnectedError extends Error { constructor() { super("Spotify is not connected yet"); this.name = "SpotifyNotConnectedError"; } }
function redirectUri(): string { return `${Deno.env.get("SUPABASE_URL")}/functions/v1/make-server-3ba8d4df/spotify/callback`; }
async function getSpotifyClientConfig(db: any): Promise<{ clientId: string; clientSecret: string }> { const { data, error } = await db.from("app_secrets").select("key, value").in("key", ["spotify_client_id", "spotify_client_secret"]); if (error) throw new Error(`Failed to load Spotify config: ${error.message}`); const map = Object.fromEntries((data ?? []).map((r: any) => [r.key, r.value])); if (!map.spotify_client_id || !map.spotify_client_secret) throw new Error("Spotify is not configured yet"); return { clientId: map.spotify_client_id, clientSecret: map.spotify_client_secret }; }
async function getValidSpotifyToken(db: any): Promise<string> { const { data, error } = await db.from("tt_spotify_auth").select("*").eq("id", 1).maybeSingle(); if (error) throw new Error(`Failed to load Spotify auth: ${error.message}`); if (!data?.refresh_token) throw new SpotifyNotConnectedError(); const expiresAtMs = data.expires_at ? new Date(data.expires_at).getTime() : 0; if (data.access_token && expiresAtMs > Date.now() + 60000) return data.access_token; const { clientId, clientSecret } = await getSpotifyClientConfig(db); const body = new URLSearchParams({ grant_type: "refresh_token", refresh_token: data.refresh_token }); const res = await fetch("https://accounts.spotify.com/api/token", { method: "POST", headers: { "Content-Type": "application/x-www-form-urlencoded", Authorization: `Basic ${btoa(`${clientId}:${clientSecret}`)}` }, body }); const json = await res.json().catch(() => ({})); if (!res.ok) throw new Error(`Spotify token refresh failed: ${json.error_description || json.error || res.statusText}`); const accessToken = json.access_token; const refreshToken = json.refresh_token ?? data.refresh_token; const expiresAt = new Date(Date.now() + (json.expires_in ?? 3600) * 1000).toISOString(); const { error: updateErr } = await db.from("tt_spotify_auth").update({ access_token: accessToken, refresh_token: refreshToken, expires_at: expiresAt, updated_at: new Date().toISOString() }).eq("id", 1); if (updateErr) console.error("Failed to persist refreshed Spotify token", updateErr); return accessToken; }
async function spotifyApi(token: string, path: string, init: RequestInit = {}): Promise<any> { const res = await fetch(`https://api.spotify.com/v1${path}`, { ...init, headers: { Authorization: `Bearer ${token}`, "Content-Type": "application/json", ...(init.headers ?? {}) } }); const text = await res.text(); let json: any = null; if (text) { try { json = JSON.parse(text); } catch { json = text; } } if (!res.ok) { const msg = json?.error?.message || (typeof json === "string" ? json : res.statusText); throw Object.assign(new Error(`Spotify API error (${res.status}): ${msg}`), { status: res.status }); } return json; }
async function withSpotify(c: any, db: any, fn: (token: string) => Promise<any>) { try { const token = await getValidSpotifyToken(db); return await fn(token); } catch (e: any) { if (e instanceof SpotifyNotConnectedError) return c.json({ error: "not_connected" }, 409); const status = e?.status; console.error("Spotify request failed", e); if (status === 403) return c.json({ error: "Spotify Premium is required to control playback." }, 403); if (status === 404) return c.json({ error: "No active Spotify device found — open Spotify on a device first." }, 404); return c.json({ error: String(e instanceof Error ? e.message : e) }, 500); } }
function mapTrack(t: any) { if (!t) return null; return { id: t.id, uri: t.uri, name: t.name, artists: (t.artists ?? []).map((a: any) => a.name).join(", "), album: t.album?.name ?? null, albumArt: t.album?.images?.[0]?.url ?? t.album?.images?.[1]?.url ?? null, durationMs: t.duration_ms ?? 0 }; }
function mapDevice(d: any) { return { id: d.id, name: d.name, type: d.type, isActive: !!d.is_active, volumePercent: d.volume_percent ?? null }; }
function oauthPage(title: string, body: string): string { return `<!doctype html><html><head><meta charset="utf-8"><title>${title}</title><style>
      body{font-family:-apple-system,BlinkMacSystemFont,sans-serif;background:#000;color:#fff;display:flex;align-items:center;justify-content:center;height:100vh;margin:0;text-align:center;padding:24px;box-sizing:border-box}
      div{max-width:340px}h1{font-size:16px;font-weight:600;margin-bottom:8px}p{font-size:13px;color:rgba(255,255,255,0.6);line-height:1.5}
    </style></head><body><div><h1>${title}</h1><p>${body}</p></div><script>setTimeout(()=>window.close(),1800)</script></body></html>`; }

export function registerSpotifyRoutes(app: Hono) {
  app.get(`${PREFIX}/spotify/status`, async (c) => { const db = supabaseAdmin(); try { const { data } = await db.from("tt_spotify_auth").select("refresh_token").eq("id", 1).maybeSingle(); if (!data?.refresh_token) return c.json({ connected: false }); const token = await getValidSpotifyToken(db); const me = await spotifyApi(token, "/me"); await db.from("tt_spotify_auth").update({ display_name: me.display_name ?? null, product: me.product ?? null, spotify_user_id: me.id ?? null }).eq("id", 1); return c.json({ connected: true, displayName: me.display_name ?? null, isPremium: me.product === "premium" }); } catch (e) { console.error("spotify status failed", e); return c.json({ connected: false, error: String(e instanceof Error ? e.message : e) }); } });
  app.get(`${PREFIX}/spotify/auth-url`, async (c) => { try { const db = supabaseAdmin(); const { clientId } = await getSpotifyClientConfig(db); const state = crypto.randomUUID(); const { error } = await db.from("tt_spotify_oauth_state").upsert({ id: 1, state, created_at: new Date().toISOString() }); if (error) throw new Error(error.message); const params = new URLSearchParams({ client_id: clientId, response_type: "code", redirect_uri: redirectUri(), scope: SPOTIFY_SCOPES, state, show_dialog: "true" }); return c.json({ url: `https://accounts.spotify.com/authorize?${params.toString()}` }); } catch (e) { console.error("spotify auth-url failed", e); return c.json({ error: String(e instanceof Error ? e.message : e) }, 500); } });
  app.get(`${PREFIX}/spotify/callback`, async (c) => { const page = (title: string, body: string) => c.html(oauthPage(title, body)); try { const url = new URL(c.req.url); const code = url.searchParams.get("code"); const state = url.searchParams.get("state"); if (url.searchParams.get("error")) return page("Connection cancelled", "Spotify sign-in was cancelled. Close this window and try again."); if (!code || !state) return page("Something went wrong", "Missing authorization code. Close this window and try connecting again."); const db = supabaseAdmin(); const { data: stateRow } = await db.from("tt_spotify_oauth_state").select("state").eq("id", 1).maybeSingle(); if (!stateRow || stateRow.state !== state) return page("Something went wrong", "This sign-in link expired or was already used. Close this window and try again."); const { clientId, clientSecret } = await getSpotifyClientConfig(db); const body = new URLSearchParams({ grant_type: "authorization_code", code, redirect_uri: redirectUri() }); const res = await fetch("https://accounts.spotify.com/api/token", { method: "POST", headers: { "Content-Type": "application/x-www-form-urlencoded", Authorization: `Basic ${btoa(`${clientId}:${clientSecret}`)}` }, body }); const json = await res.json().catch(() => ({})); if (!res.ok) throw new Error(json.error_description || json.error || res.statusText); const accessToken = json.access_token, refreshToken = json.refresh_token; const expiresAt = new Date(Date.now() + (json.expires_in ?? 3600) * 1000).toISOString(); let profile: any = {}; try { profile = await spotifyApi(accessToken, "/me"); } catch (e) { console.warn("Could not fetch Spotify profile after connect", e); } const { error: upsertErr } = await db.from("tt_spotify_auth").upsert({ id: 1, access_token: accessToken, refresh_token: refreshToken, expires_at: expiresAt, scope: json.scope ?? SPOTIFY_SCOPES, spotify_user_id: profile.id ?? null, display_name: profile.display_name ?? null, product: profile.product ?? null, updated_at: new Date().toISOString() }); if (upsertErr) throw new Error(upsertErr.message); await db.from("tt_spotify_oauth_state").delete().eq("id", 1); return page("Spotify connected", `Signed in as ${profile.display_name ?? "your account"}. You can close this window.`); } catch (e) { console.error("spotify callback failed", e); return page("Something went wrong", String(e instanceof Error ? e.message : e)); } });
  app.post(`${PREFIX}/spotify/disconnect`, async (c) => { try { const db = supabaseAdmin(); const { error } = await db.from("tt_spotify_auth").delete().eq("id", 1); if (error) throw new Error(error.message); return c.json({ ok: true }); } catch (e) { return c.json({ error: String(e instanceof Error ? e.message : e) }, 500); } });
  app.get(`${PREFIX}/spotify/now-playing`, async (c) => { const db = supabaseAdmin(); return withSpotify(c, db, async (token) => { const res = await fetch("https://api.spotify.com/v1/me/player", { headers: { Authorization: `Bearer ${token}` } }); if (res.status === 204 || res.status === 404) return c.json({ isPlaying: false, item: null, device: null, progressMs: 0 }); const json = await res.json().catch(() => ({})); if (!res.ok) throw Object.assign(new Error(json?.error?.message || res.statusText), { status: res.status }); return c.json({ isPlaying: !!json.is_playing, progressMs: json.progress_ms ?? 0, item: mapTrack(json.item), device: json.device ? mapDevice(json.device) : null, shuffle: !!json.shuffle_state, repeat: json.repeat_state ?? "off" }); }); });
  app.get(`${PREFIX}/spotify/devices`, async (c) => { const db = supabaseAdmin(); return withSpotify(c, db, async (token) => { const res = await spotifyApi(token, "/me/player/devices"); return c.json({ devices: (res.devices ?? []).map(mapDevice) }); }); });
  app.post(`${PREFIX}/spotify/play`, async (c) => { const db = supabaseAdmin(); const { deviceId, uri, contextUri } = await c.req.json().catch(() => ({})); return withSpotify(c, db, async (token) => { const q = deviceId ? `?device_id=${encodeURIComponent(deviceId)}` : ""; const body = uri ? { uris: [uri] } : contextUri ? { context_uri: contextUri } : {}; await spotifyApi(token, `/me/player/play${q}`, { method: "PUT", body: JSON.stringify(body) }); return c.json({ ok: true }); }); });
  app.post(`${PREFIX}/spotify/pause`, async (c) => { const db = supabaseAdmin(); const { deviceId } = await c.req.json().catch(() => ({})); return withSpotify(c, db, async (token) => { const q = deviceId ? `?device_id=${encodeURIComponent(deviceId)}` : ""; await spotifyApi(token, `/me/player/pause${q}`, { method: "PUT" }); return c.json({ ok: true }); }); });
  app.post(`${PREFIX}/spotify/next`, async (c) => { const db = supabaseAdmin(); const { deviceId } = await c.req.json().catch(() => ({})); return withSpotify(c, db, async (token) => { const q = deviceId ? `?device_id=${encodeURIComponent(deviceId)}` : ""; await spotifyApi(token, `/me/player/next${q}`, { method: "POST" }); return c.json({ ok: true }); }); });
  app.post(`${PREFIX}/spotify/previous`, async (c) => { const db = supabaseAdmin(); const { deviceId } = await c.req.json().catch(() => ({})); return withSpotify(c, db, async (token) => { const q = deviceId ? `?device_id=${encodeURIComponent(deviceId)}` : ""; await spotifyApi(token, `/me/player/previous${q}`, { method: "POST" }); return c.json({ ok: true }); }); });
  app.post(`${PREFIX}/spotify/volume`, async (c) => { const db = supabaseAdmin(); const { volumePercent, deviceId } = await c.req.json().catch(() => ({})); return withSpotify(c, db, async (token) => { const params = new URLSearchParams({ volume_percent: String(Math.max(0, Math.min(100, Math.round(volumePercent ?? 50)))) }); if (deviceId) params.set("device_id", deviceId); await spotifyApi(token, `/me/player/volume?${params.toString()}`, { method: "PUT" }); return c.json({ ok: true }); }); });
  app.post(`${PREFIX}/spotify/seek`, async (c) => { const db = supabaseAdmin(); const { positionMs, deviceId } = await c.req.json().catch(() => ({})); return withSpotify(c, db, async (token) => { const params = new URLSearchParams({ position_ms: String(Math.max(0, Math.round(positionMs ?? 0))) }); if (deviceId) params.set("device_id", deviceId); await spotifyApi(token, `/me/player/seek?${params.toString()}`, { method: "PUT" }); return c.json({ ok: true }); }); });
  app.post(`${PREFIX}/spotify/transfer`, async (c) => { const db = supabaseAdmin(); const { deviceId, play } = await c.req.json().catch(() => ({})); if (!deviceId) return c.json({ error: "deviceId is required" }, 400); return withSpotify(c, db, async (token) => { await spotifyApi(token, "/me/player", { method: "PUT", body: JSON.stringify({ device_ids: [deviceId], play: !!play }) }); return c.json({ ok: true }); }); });
  app.get(`${PREFIX}/spotify/search`, async (c) => { const db = supabaseAdmin(); const q = c.req.query("q") ?? ""; if (!q.trim()) return c.json({ tracks: [] }); return withSpotify(c, db, async (token) => { const params = new URLSearchParams({ q, type: "track", limit: "12" }); const res = await spotifyApi(token, `/search?${params.toString()}`); return c.json({ tracks: (res.tracks?.items ?? []).map(mapTrack) }); }); });
  app.get(`${PREFIX}/spotify/upcoming`, async (c) => { const db = supabaseAdmin(); return withSpotify(c, db, async (token) => { const res = await spotifyApi(token, "/me/player/queue"); return c.json({ currentlyPlaying: mapTrack(res.currently_playing), queue: (res.queue ?? []).slice(0, 10).map(mapTrack) }); }); });
  app.post(`${PREFIX}/spotify/queue`, async (c) => { const db = supabaseAdmin(); const { uri, deviceId } = await c.req.json().catch(() => ({})); if (!uri) return c.json({ error: "uri is required" }, 400); return withSpotify(c, db, async (token) => { const params = new URLSearchParams({ uri }); if (deviceId) params.set("device_id", deviceId); await spotifyApi(token, `/me/player/queue?${params.toString()}`, { method: "POST" }); return c.json({ ok: true }); }); });
}
